# https://help.github.com/en/actions/building-actions/metadata-syntax-for-github-actions
name: "Limit Pull Requests"
description: "Limits pull requests to given branches"
author: "luk.bukkit@gmail.com"

runs:
  using: 'node16'
  main: 'lib/index.js'

inputs:
  # Still supported, but deprecated
  whitelist:
    description: "A list of allowed branches"
    required: false
    default: ''
    deprecationMessage: 'The input `whitelist` is deprecated, use `allowlist`'
  # Still supported, but deprecated
  blacklist:
    description: "A list of forbidden branches"
    required: false
    default: ''
    deprecationMessage: 'The input `blacklist` is deprecated, use `denylist`'
  allowlist:
    description: "A list of allowed branches"
    required: false
    default: ''
  denylist:
    description: "A list of forbidden branches"
    required: false
    default: ''
  local:
    description: 'Set to `true` to only accept pull requests from the local repository'
    required: false
    default: 'false'


branding:
  color: "orange"
  icon: "shield"
